// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bowtoiszqyqwauuwkuwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvd3RvaXN6cXlxd2F1dXdrdXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzUwNDksImV4cCI6MjA3NDExMTA0OX0.d1q6OUAOUGFNLXh5vUcS813qXh8U7k9tLPwD8dt3rY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});